GitHub Sponsors: github.com/sponsors/DeonteWattsV1
• Patreon: https://www.patreon.com/cw/GetitD
• Open Collective: https://opencollective.com/deontewattsv1
• Ko-fi: https://ko-fi.com/deontewattsv1
• Tidelift: https://sonarcloud.io/organizations/deontewattsv1/
• Community Bridge / LFX Crowdfunding: crowdfunding.lfx.linuxfoundation.org/deontewattssV1
• Liberapay: https://liberapay.com/DeontewattsV1/
• IssueHunt: https://issuehunt.io/profiles/deontewattsv1
• Polar: https://polar.sh/dashboard/deonte-watts
• Buy Me a Coffee: https://buymeacoffee.com/deontewattsv1
• thanks.dev: https://thanks.dev/e/gh/deontewattsv1
. Venmo: https://venmo.com/u/Goodstuff966
. Cashapp: https://cash.app/$yippeeyioo
