import { OctaTheme, OctaThemeName } from './types';

const baseTypography = {
  displayLg: { fontSize: 34, lineHeight: 40, fontWeight: '700', letterSpacing: -0.7 },
  displayMd: { fontSize: 28, lineHeight: 34, fontWeight: '700', letterSpacing: -0.45 },
  titleLg: { fontSize: 22, lineHeight: 28, fontWeight: '600', letterSpacing: -0.25 },
  titleMd: { fontSize: 18, lineHeight: 24, fontWeight: '600', letterSpacing: -0.15 },
  bodyLg: { fontSize: 17, lineHeight: 24, fontWeight: '400' },
  bodyMd: { fontSize: 15, lineHeight: 22, fontWeight: '400' },
  bodySm: { fontSize: 13, lineHeight: 18, fontWeight: '400' },
  labelLg: { fontSize: 16, lineHeight: 20, fontWeight: '600', letterSpacing: 0.1 },
  labelMd: { fontSize: 14, lineHeight: 18, fontWeight: '600', letterSpacing: 0.1 },
  labelSm: { fontSize: 12, lineHeight: 16, fontWeight: '600', letterSpacing: 0.2 },
  monoSm: { fontSize: 12, lineHeight: 16, fontWeight: '500', letterSpacing: 0.15 },
} as const;

const baseSpacing = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  xxxl: 40,
} as const;

const baseRadius = {
  xs: 10,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  pill: 999,
} as const;

const buildTheme = (theme: OctaTheme): OctaTheme => theme;

export const octaThemes: Record<OctaThemeName, OctaTheme> = {
  midnight: buildTheme({
    name: 'midnight',
    dark: true,
    colors: {
      background: '#0B1020',
      backgroundAlt: '#0E1427',
      surface: '#12182B',
      surfaceElevated: '#1A2238',
      surfaceSunken: '#0F1526',
      textPrimary: '#F5F7FB',
      textSecondary: '#A7B0C2',
      textMuted: '#7C869C',
      border: '#26314D',
      outline: 'rgba(155, 140, 255, 0.32)',
      primary: '#7C5CFF',
      primaryGlow: '#9B8CFF',
      secondary: '#2DD4BF',
      success: '#22C55E',
      warning: '#F59E0B',
      danger: '#EF4444',
      info: '#60A5FA',
      inverseText: '#0B1020',
      chatUserBubble: '#7C5CFF',
      chatAssistantBubble: '#151D31',
      chatSystemBubble: '#111827',
      gestureCyan: '#43D9FF',
      gestureMagenta: '#FF38D1',
      gestureLime: '#C7FF2F',
    },
    gradients: {
      hero: ['#0B1020', '#12182B', '#1A2238'],
      accent: ['#7C5CFF', '#9B8CFF'],
      gestureRing: ['#43D9FF', '#FF38D1', '#C7FF2F'],
    },
    radius: baseRadius,
    spacing: baseSpacing,
    typography: baseTypography,
    shadows: {
      soft: {
        shadowColor: '#000000',
        shadowOpacity: 0.16,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 8 },
        elevation: 8,
      },
      glow: {
        shadowColor: '#7C5CFF',
        shadowOpacity: 0.32,
        shadowRadius: 22,
        shadowOffset: { width: 0, height: 8 },
        elevation: 10,
      },
    },
    motion: {
      quick: 120,
      standard: 180,
      slow: 260,
    },
  }),
  pearl: buildTheme({
    name: 'pearl',
    dark: false,
    colors: {
      background: '#F7F8FC',
      backgroundAlt: '#EFF3FA',
      surface: '#FFFFFF',
      surfaceElevated: '#EEF2FF',
      surfaceSunken: '#E8EDF7',
      textPrimary: '#0F172A',
      textSecondary: '#475569',
      textMuted: '#64748B',
      border: '#D9E1F2',
      outline: 'rgba(79, 70, 229, 0.25)',
      primary: '#4F46E5',
      primaryGlow: '#818CF8',
      secondary: '#06B6D4',
      success: '#16A34A',
      warning: '#D97706',
      danger: '#DC2626',
      info: '#2563EB',
      inverseText: '#F8FAFC',
      chatUserBubble: '#4F46E5',
      chatAssistantBubble: '#FFFFFF',
      chatSystemBubble: '#EEF2FF',
      gestureCyan: '#06B6D4',
      gestureMagenta: '#D946EF',
      gestureLime: '#84CC16',
    },
    gradients: {
      hero: ['#F7F8FC', '#EEF2FF', '#E0E7FF'],
      accent: ['#4F46E5', '#818CF8'],
      gestureRing: ['#06B6D4', '#D946EF', '#84CC16'],
    },
    radius: baseRadius,
    spacing: baseSpacing,
    typography: baseTypography,
    shadows: {
      soft: {
        shadowColor: '#020617',
        shadowOpacity: 0.08,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 6 },
        elevation: 6,
      },
      glow: {
        shadowColor: '#4F46E5',
        shadowOpacity: 0.18,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 8 },
        elevation: 8,
      },
    },
    motion: {
      quick: 120,
      standard: 180,
      slow: 260,
    },
  }),
  obsidian: buildTheme({
    name: 'obsidian',
    dark: true,
    colors: {
      background: '#050816',
      backgroundAlt: '#090E20',
      surface: '#0E1326',
      surfaceElevated: '#141B34',
      surfaceSunken: '#0A1020',
      textPrimary: '#F8FAFC',
      textSecondary: '#94A3B8',
      textMuted: '#64748B',
      border: '#24304A',
      outline: 'rgba(139, 92, 246, 0.35)',
      primary: '#8B5CF6',
      primaryGlow: '#A78BFA',
      secondary: '#22D3EE',
      success: '#22C55E',
      warning: '#F59E0B',
      danger: '#F43F5E',
      info: '#38BDF8',
      inverseText: '#050816',
      chatUserBubble: '#8B5CF6',
      chatAssistantBubble: '#121B31',
      chatSystemBubble: '#0F172A',
      gestureCyan: '#22D3EE',
      gestureMagenta: '#F472B6',
      gestureLime: '#A3E635',
    },
    gradients: {
      hero: ['#050816', '#0E1326', '#141B34'],
      accent: ['#8B5CF6', '#A78BFA'],
      gestureRing: ['#22D3EE', '#F472B6', '#A3E635'],
    },
    radius: baseRadius,
    spacing: baseSpacing,
    typography: baseTypography,
    shadows: {
      soft: {
        shadowColor: '#000000',
        shadowOpacity: 0.2,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 10 },
        elevation: 10,
      },
      glow: {
        shadowColor: '#8B5CF6',
        shadowOpacity: 0.35,
        shadowRadius: 24,
        shadowOffset: { width: 0, height: 10 },
        elevation: 12,
      },
    },
    motion: {
      quick: 120,
      standard: 180,
      slow: 260,
    },
  }),
};

export const createOctaTheme = (name: OctaThemeName = 'midnight'): OctaTheme => octaThemes[name];
